/**
 * YAML Utilities
 * 
 * Comment-aware YAML serialization for simplens.config.yaml.
 */

import { readFile } from 'fs/promises';
import { parse as yamlParse } from 'yaml';

export interface ProviderEntry {
    package: string;
    id: string;
    credentials: Record<string, string>;
    optionalConfig?: Record<string, string>;
    options?: {
        priority?: number;
        rateLimit?: { maxTokens?: number; refillRate?: number };
    };
}

export interface SimpleNSConfig {
    providers: ProviderEntry[];
    channels: Record<string, { default: string; fallback?: string }>;
}

/**
 * Parse an existing config file
 */
export async function parseExistingConfig(filePath: string): Promise<SimpleNSConfig> {
    const content = await readFile(filePath, 'utf-8');
    return yamlParse(content) as SimpleNSConfig;
}

/**
 * Serialize config to YAML with helpful comments
 */
export function serializeConfigWithComments(config: SimpleNSConfig): string {
    const lines: string[] = [];

    // Header comment
    lines.push('# ============================================');
    lines.push('# SimpleNS Configuration');
    lines.push('# Generated by @simplens/config-gen');
    lines.push('# ============================================');
    lines.push('');

    // Providers section
    lines.push('# Provider configurations');
    lines.push('# Each provider connects to an external notification service');
    lines.push('providers:');

    for (const provider of config.providers) {
        lines.push(`  # ${provider.id} - ${provider.package}`);
        lines.push(`  - package: "${provider.package}"`);
        lines.push(`    id: ${provider.id}`);

        // Credentials
        lines.push('    credentials:');
        if (Object.keys(provider.credentials).length === 0) {
            lines.push('      {} # No credentials required');
        } else {
            for (const [key, value] of Object.entries(provider.credentials)) {
                lines.push(`      ${key}: ${value}  # Required`);
            }
        }

        // Optional config
        if (provider.optionalConfig && Object.keys(provider.optionalConfig).length > 0) {
            lines.push('    optionalConfig:');
            for (const [key, value] of Object.entries(provider.optionalConfig)) {
                lines.push(`      ${key}: ${value}  # Optional`);
            }
        }

        // Options
        lines.push('    options:');
        lines.push(`      priority: ${provider.options?.priority || 1}  # Higher = preferred`);
        lines.push('      rateLimit:');
        lines.push(`        maxTokens: ${provider.options?.rateLimit?.maxTokens || 100}  # Token bucket capacity`);
        lines.push(`        refillRate: ${provider.options?.rateLimit?.refillRate || 10}  # Tokens per second`);
        lines.push('');
    }

    // Channels section
    lines.push('# Channel to provider mapping');
    lines.push('# Maps notification channels to their default (and optional fallback) providers');
    lines.push('channels:');

    for (const [channel, mapping] of Object.entries(config.channels)) {
        lines.push(`  ${channel}:`);
        lines.push(`    default: ${mapping.default}  # Primary provider for ${channel}`);
        if (mapping.fallback) {
            lines.push(`    fallback: ${mapping.fallback}  # Used if default fails`);
        }
    }

    return lines.join('\n') + '\n';
}
